# Generated by Django 3.2.8 on 2022-04-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cmtDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentID', models.CharField(max_length=4)),
                ('cmtText', models.TextField()),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='blogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogID', models.CharField(max_length=4)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cmtdetail')),
                ('ownerUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdetail')),
            ],
        ),
    ]
